# Generated by Django 5.1.3 on 2024-11-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
