# Generated by Django 5.1.3 on 2024-11-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_alter_client_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
