# Generated by Django 5.1.3 on 2024-11-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0013_alter_caseprogress_progress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseprogress',
            name='unique_info',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
